### ISSUE TITLE
Investigate the difference between `csv`s and `accsdb` file

### ISSUE THREAD

**Issue by 5cat** [2023-CITS3200-34/CITS3200_34#19]
The client provided us with `csv`s files and `accsdb` file, we are not sure if they are equivalent. 

Please investigate the difference between them.

**Comment by thomasd-b** [comment]
**CSV FILES:**
A CSV (Comma-Separated Values) file is a simple and widely used file format for storing and exchanging structured data. It is a plain text file where data is organized in rows and columns, with each line representing a single record or data entry, and the values within each line separated by commas (or other delimiters, such as tabs or semicolons).

CSV files are commonly used for various purposes, including data storage, data transfer between different software applications, and data analysis. They are easy to create and read using text editors, spreadsheet software like Microsoft Excel or Google Sheets, and programming languages like Python.


**ACCDB FILES:**
An ACCDB file is a file format associated with Microsoft Access, a relational database management system (RDBMS). ACCDB stands for "Access Database" and is used to store and manage structured data in a database. This file format was introduced with Microsoft Access 2007 and is an improvement over the older .MDB (Microsoft Database) file format used in earlier versions of Access.

Key characteristics of ACCDB files include:

_Relational Database_: ACCDB files are used to create and manage relational databases. They allow you to define tables, relationships between tables, queries, forms, and reports, among other database objects.

_Tables: In an ACCDB file_: you can create tables to store data. These tables consist of rows and columns, similar to a spreadsheet, but with more advanced capabilities for handling structured data.

_Queries_: You can create queries to extract, filter, and manipulate data from your tables. Queries allow you to retrieve specific information from the database based on specified criteria.

_Forms_: Forms in Access are used to create user-friendly interfaces for interacting with the database. They can be customized to display data, accept input, and trigger actions.

_Reports_: Reports allow you to generate formatted and printable output from your database. You can design reports to present data in a visually appealing and organized manner.

_Data Macros_: ACCDB files also support data macros, which are similar to triggers in other database systems. Data macros can automate actions based on data changes, helping to enforce business rules.

_Security_: Microsoft Access provides features for securing ACCDB files, including user-level security and password protection.

_Integration_: ACCDB files can be integrated with other Microsoft Office applications like Excel and Word. You can import and export data between these applications and Access.

ACCDB files are typically used for small to medium-sized databases, departmental databases, or personal projects. For larger and more complex databases, Microsoft SQL Server or other enterprise-level database management systems are often preferred.

_To work with ACCDB files, you'll need Microsoft Access or compatible database software that can open and manipulate this file format._
