### ISSUE TITLE
Add all contact fields in the django model for contacts

### ISSUE THREAD

**Issue by 5cat** [2023-CITS3200-34/CITS3200_34#38]
Edit the columns to match the bellow schema
![image](https://github.com/2023-CITS3200-34/CITS3200_34/assets/42038325/ec030b50-f9b8-4316-a54b-80b18f518bbb)

**Comment by Jamlons** [comment]
Added PULL request https://github.com/2023-CITS3200-34/CITS3200_34/pull/42

**Comment by Jamlons** [comment]
Updated and pull request in.
