### ISSUE TITLE
Design initial frontend page for adding contacts

### ISSUE THREAD

**Issue by 5cat** [2023-CITS3200-34/CITS3200_34#6]
Use tools such as figma to design a web page design so it can be implemented in code.

Keep in mind that contacts can be added, deleted, displayed, and edited

**Comment by yebenti** [comment]
https://www.figma.com/file/3ZCW5XCPfUoq24fo7VBysE/Contacts-Page?type=design&mode=design&t=ff9rCtGNDgRWc7SV-1

The password is: 
34
